[package]
name = "myanon"
version = "0.1.0"
edition = "2021"

[features]
default = []
python = ["pyo3"]

[dependencies]
regex = "1"
hmac = "0.12"
sha2 = "0.10"
pyo3 = { version = "0.23", features = ["auto-initialize"], optional = true }
